POST https://50bw7bq4r6.execute-api.us-east-1.amazonaws.com/prod/icecream HTTP/1.1
content-type: application/json

{
    "name": "Chocolate",
    "ingredients": [
      {
        "name": "Chocolate"
      },
      {
        "name": "Milk"
      }
    ]
}